import { useState } from 'react';
import { IconSearch } from '@/components/Icons';
import { updatePreviewPlace, type Job } from '@/core/jobs';

type PoiCandidate = NonNullable<NonNullable<Job['amapPoiMatches']>[string]['candidates']>[number];

export function RouteSummary({ route }: { route: Extract<Job['items'][number], { kind: 'route' }> }) {
  const roleName: Record<string, string> = { start: '起点', waypoint: '途经点', end: '终点' };
  return <article className="route-summary"><div className="route-summary-head"><strong>{route.name}</strong><span>{route.travelMode ?? route.routing.transitKind ?? '路线'}</span></div><ol>{route.stops.map((stop) => <li key={`${stop.role}-${stop.point.lng}-${stop.point.lat}`}><span>{roleName[stop.role] ?? stop.role}：{stop.name}</span><code>{stop.point.lng.toFixed(5)}, {stop.point.lat.toFixed(5)}</code></li>)}</ol></article>;
}

export function PlaceTable({ places, onChange, canMatchAmap, amapPoiMatches, amapPoiResolutions, matchingPlaceIds, matching, onMatchAmapPoi, onMatchAmapPage, onSelectAmapPoi }: {
  places: Job['places']; onChange: (places: Job['places']) => void; canMatchAmap?: boolean; amapPoiMatches?: Job['amapPoiMatches']; amapPoiResolutions?: Job['amapPoiResolutions']; matchingPlaceIds?: Set<string>; matching?: boolean; onMatchAmapPoi?: (placeId: string) => void; onMatchAmapPage?: (placeIds: string[]) => void; onSelectAmapPoi?: (placeId: string, candidate?: PoiCandidate) => void;
}) {
  const [filter, setFilter] = useState(''); const [searchOpen, setSearchOpen] = useState(false); const [pageSize, setPageSize] = useState<10 | 30 | 50>(10); const [page, setPage] = useState(1);
  const filtered = places.filter((p) => !filter || p.name.toLowerCase().includes(filter.toLowerCase()) || (p.address ?? '').toLowerCase().includes(filter.toLowerCase())); const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(page, pageCount); const shown = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const updateFilter = (value: string) => { setFilter(value); setPage(1); }; const update = (id: string, patch: Partial<Job['places'][number]>) => onChange(places.map((p) => (p.id === id ? updatePreviewPlace(p, patch) : p))); const remove = (id: string) => onChange(places.filter((p) => p.id !== id));
  return <div className={`place-table${canMatchAmap ? ' can-match' : ''}`}>
    <div className="place-toolbar"><label className="page-size" title="每页显示数量"><span>每页显示</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value) as 10 | 30 | 50); setPage(1); }}><option value="10">10条</option><option value="30">30条</option><option value="50">50条</option></select></label><div className="place-search"><button className={`small icon-button${searchOpen ? ' active' : ''}`} aria-label="搜索地点" title="搜索地点" aria-expanded={searchOpen} onClick={() => setSearchOpen((open) => !open)}><IconSearch /></button>{searchOpen && <div className="place-search-popover"><input autoFocus className="filter" placeholder="搜索名称 / 地址…" value={filter} onChange={(e) => updateFilter(e.target.value)} />{filter && <button className="small icon-button" aria-label="清除搜索" title="清除搜索" onClick={() => updateFilter('')}>×</button>}</div>}</div>{canMatchAmap && <button className="small secondary page-match" disabled={shown.length === 0 || matching === true || (matchingPlaceIds?.size ?? 0) > 0} onClick={() => onMatchAmapPage?.(shown.map((place) => place.id))}>{matching ? '匹配中…' : '尝试地址匹配'}</button>}</div>
    <div className="table-head"><span></span><span>名称</span><span>地址</span>{canMatchAmap && <span className="match-heading">地址匹配 <span className="column-help" title="通过目标地图的 POI 搜索，将导入地点关联到目标地图中的原生地点，以便显示正确的名称和地点信息。" aria-label="地址匹配说明">?</span></span>}</div><div className="table-body">{shown.map((place) => <PlaceRow key={place.id} place={place} canMatchAmap={canMatchAmap} match={amapPoiMatches?.[place.id]} resolution={amapPoiResolutions?.[place.id]} matching={matchingPlaceIds?.has(place.id) ?? false} disabled={matchingPlaceIds !== undefined && matchingPlaceIds.size > 0} onChange={update} onRemove={remove} onMatch={onMatchAmapPoi} onSelect={onSelectAmapPoi} />)}{shown.length === 0 && <div className="empty">无匹配</div>}</div><div className="table-foot"><span>共 {places.length} 条，匹配 {filtered.length} 条，当前 {currentPage}/{pageCount} 页</span>{pageCount > 1 && <div className="pagination" aria-label="地点分页"><button className="small ghost" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>‹</button><button className="small ghost" disabled={currentPage === pageCount} onClick={() => setPage(currentPage + 1)}>›</button></div>}</div>
  </div>;
}

function PlaceRow({ place, canMatchAmap, match, resolution, matching, disabled, onChange, onRemove, onMatch, onSelect }: { place: Job['places'][number]; canMatchAmap?: boolean; match?: NonNullable<Job['amapPoiMatches']>[string]; resolution?: NonNullable<Job['amapPoiResolutions']>[string]; matching: boolean; disabled: boolean; onChange: (id: string, patch: Partial<Job['places'][number]>) => void; onRemove: (id: string) => void; onMatch?: (placeId: string) => void; onSelect?: (placeId: string, candidate?: PoiCandidate) => void; }) {
  const [diagnosticOpen, setDiagnosticOpen] = useState(false);
  return <div className="place-row"><div className="row"><button className="remove" aria-label={`删除${place.name}`} title="删除此记录" onClick={() => onRemove(place.id)}>✕</button><input value={place.name} title={`名称：${place.name}\nWGS-84：${place.wgs84.lng.toFixed(6)}, ${place.wgs84.lat.toFixed(6)}`} onChange={(e) => onChange(place.id, { name: e.target.value })} /><input value={place.address ?? ''} title={`地址：${place.address ?? ''}`} onChange={(e) => onChange(place.id, { address: e.target.value })} />{canMatchAmap && <PoiMatchCell place={place} match={match} resolution={resolution} matching={matching} disabled={disabled} diagnosticOpen={diagnosticOpen} onToggleDiagnostic={() => setDiagnosticOpen((open) => !open)} onMatch={onMatch} onSelect={onSelect} />}</div>{import.meta.env.DEV && diagnosticOpen && match && <PoiMatchDiagnostic place={place} match={match} />}</div>;
}

function PoiMatchCell({ place, match, resolution, matching, disabled, diagnosticOpen, onToggleDiagnostic, onMatch, onSelect }: { place: Job['places'][number]; match?: NonNullable<Job['amapPoiMatches']>[string]; resolution?: NonNullable<Job['amapPoiResolutions']>[string]; matching: boolean; disabled: boolean; diagnosticOpen: boolean; onToggleDiagnostic: () => void; onMatch?: (placeId: string) => void; onSelect?: (placeId: string, candidate?: PoiCandidate) => void; }) {
  if (matching || match?.status === 'matching') return <span className="match-progress" role="status">匹配中…</span>;
  const candidates = match?.candidates ?? []; const selector = import.meta.env.DEV && candidates.length > 0 ? <select className="match-candidate-select" value={resolution?.poiid ?? ''} aria-label={`为${place.name}选择目标地图 POI`} onChange={(event) => onSelect?.(place.id, candidates.find((item) => item.poiid === event.target.value))}><option value="">无最佳匹配</option>{candidates.map((candidate, index) => { const score = Number.isFinite(candidate.nameScore) ? candidate.nameScore : 0; return <option key={candidate.poiid} value={candidate.poiid} title={`距离 ${Math.round(candidate.distanceMeters)} 米，名称相似度 ${score.toFixed(2)}${candidate.address ? `，地址：${candidate.address}` : ''}`}>{index + 1}. {candidate.name}（匹配度 {Math.round(score * 100)}%）</option>; })}</select> : null;
  const controls = <div className="match-controls"><button className="small icon-button" disabled={disabled} aria-label="刷新 POI 匹配" title="刷新 POI 匹配" onClick={() => onMatch?.(place.id)}>↻</button>{import.meta.env.DEV && <button className="small icon-button" aria-label="查看匹配原因" title="查看匹配原因" aria-expanded={diagnosticOpen} onClick={onToggleDiagnostic}>ⓘ</button>}{selector}{import.meta.env.DEV && match?.status === 'not-found' && candidates.length === 0 && <select className="match-candidate-select" value="" disabled aria-label={`为${place.name}选择高德 POI`}><option value="">未找到</option></select>}{!import.meta.env.DEV && match?.status === 'not-found' && <span className="match-status warning">未找到</span>}</div>;
  if (resolution || match?.status === 'matched' || match?.status === 'not-found') return <div className="match-cell">{controls}</div>;
  if (match?.status === 'ambiguous') return <span className="match-status warning">候选不明确<details className="match-candidates"><summary>选择</summary><ul>{(match.candidates ?? []).map((candidate) => <li key={candidate.poiid}><button className="small ghost" onClick={() => onSelect?.(place.id, candidate)}>{candidate.name}（{Math.round(candidate.distanceMeters)}m）</button></li>)}</ul></details></span>;
  if (match?.status === 'failed') return <span className="match-status warning" title={match.error}>失败 <button className="small secondary" disabled={disabled} onClick={() => onMatch?.(place.id)}>重试</button></span>;
  return <button className="small secondary" disabled={disabled} onClick={() => onMatch?.(place.id)}>匹配</button>;
}

function PoiMatchDiagnostic({ place, match }: { place: Job['places'][number]; match: NonNullable<Job['amapPoiMatches']>[string] }) {
  const [copied, setCopied] = useState(false); const best = match.candidates?.[0]; const diagnostic = [`地点：${place.name}`, `地址：${place.address || '（无）'}`, `坐标：${place.wgs84.lng.toFixed(6)}, ${place.wgs84.lat.toFixed(6)}`, `候选数量：${match.candidates?.length ?? 0}`, best ? `最佳候选：${best.name}，距离 ${Math.round(best.distanceMeters)} 米` : '', match.reason ? `原因：${match.reason}` : ''].filter(Boolean).join('\n');
  async function copyDiagnostic(): Promise<void> { try { await navigator.clipboard.writeText(diagnostic); setCopied(true); window.setTimeout(() => setCopied(false), 1500); } catch { setCopied(false); } }
  return <div className="row-diagnostic"><button className="small ghost" onClick={() => void copyDiagnostic()}>{copied ? '已复制 ✓' : '复制记录'}</button><pre>{diagnostic}</pre></div>;
}
